# namespaced resources 
# yet: clusterIP, No ingress, no TLS, no auth

apiVersion: v1
kind: Service
metadata:
  name: mxui-svc-brwoser
  namespace: mxui
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: mxui
    app.kubernetes.io/component: svc
  annotations:
     description: "ClusterIP service for the Browser"
spec:
  type: ClusterIP            # Internal-IP only - no external access. Use type LoadBalancer or Ingress for external access.
  # this kind lookup for/apply to pod with these labels
  selector: 
    app.kubernetes.io/name: browser
  ports:
    - name: port-k8-svc       # defines the service port name (used as a var)
      port: 5800              # the port the SERVICE listens on and exposes inside the cluster
      targetPort: port-ct-svc # reference to the port in the selected pod
      protocol: TCP