# clustered resources

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cimreg-sc
  labels:
    app.kubernetes.io/name: cimreg
    app.kubernetes.io/component: registry
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Persistent storage for the internal container registry cimreg"
provisioner: openebs.io/local
reclaimPolicy: Retain # When PVC is deleted, PV is not deleted; data persists on the node - see https://kubernetes.io/docs/concepts/storage/storage-classes/
volumeBindingMode: WaitForFirstConsumer # PV is created only when the pod using a PVC (taht uses that SC) is scheduled, not before
allowVolumeExpansion: true
parameters:
  storageType: hostpath # Volumes are hostPath folders 
  path: /var/lib/cimreg-local


