# namespaced resources

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimreg-deploy
  namespace: cimreg
  labels:
    app.kubernetes.io/name: cimreg
    app.kubernetes.io/component: registry
  annotations:
    description: "Docker Container Image Registry deployment using registry:3.0.0 image"
spec:
  # ensures 1 pod on 1 node
  replicas: 1
  # this deployment concerns pod with this label
  selector:
    matchLabels:
      app.kubernetes.io/name: cimreg
      app.kubernetes.io/component: registry
  # when creating pod, use this pod definition
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cimreg
        app.kubernetes.io/component: registry
    spec:
      # # Pod must be schedule where the provisioner is provisioned
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: openebs.io/nodename
      #           operator: Exists
      containers:  
        - name: cregistry                   # 1. The Container Identity
          image: registry:3.0.0
          env:
          - name: REGISTRY_TRACING_ENABLED # disable tracing (opentelemetry) - avoid error logs
            value: "false"
          - name: OTEL_TRACES_EXPORTER 
            value: "none"  
          ports:
            - containerPort: 5000
              name: port-ct-svc                 # 2. The Container Port label (used as a var)
          # --- PART 2: THE DESTINATION ---
          volumeMounts:
            - name: registry-storage        # Matches the volume name below
              mountPath: /var/lib/registry  # mount point inside the container              
          # --- PROBES START HERE ---
          # Checks if the app inside the container is alive. If this fails, K8s kills and restarts the pod.
          livenessProbe:
            httpGet:
              path: /v2/
              port: port-ct-svc
            initialDelaySeconds: 15
            periodSeconds: 20          
          # Checks if the app inside the container is ready for traffic. If this fails, the Service stops sending traffic here.
          readinessProbe:
            httpGet:
              path: /v2/
              port: port-ct-svc
            initialDelaySeconds: 5
            periodSeconds: 10
          # --- PROBES END HERE ---                    
      # --- PART 1: THE SOURCE ---
      volumes:
        - name: registry-storage  # a uniq name for the volume
          persistentVolumeClaim:
            claimName: cimreg-pvc # the PVC (data-source)

