apiVersion: v2
name: cimreg
description: an OCI artifact registry for container images, Helm charts, ...
type: application

# chart version
# bump version when chart templates change
# Every merge to main → bump chart version.
version: 0.1.0

# app version - Keep appVersion aligned with the container image tag
appVersion: "0.1.0"
