# namespaced resources

{{- if or .Values.enabled.all .Values.enabled.mnf.cm }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cimreg-cm
  # namespace is injected by helm
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: cimreg
  annotations:
    owner: "abtransitionit"
    description: "stores the paramters for the app:cimreg"
data:
  CIMREG_HOSTPATH: {{ .Values.cimreg.hostPath | quote }}
{{- end }}

