apiVersion: v2 # helm v3 mandatory
name: mxui
description: accessible UI as a services like browser, interactive bash shell, sonarqube, nexus, ... 
type: application

# chart version
# bump version when chart templates change
# Every merge to main → bump chart version.
version: 0.1.0

# app version - Keep appVersion aligned with the container image tag
appVersion: "0.1.0"
