# clustered resources

apiVersion: v1
kind: Namespace
metadata:
  name: cimreg

  labels:
    app.kubernetes.io/component: registry
    app.kubernetes.io/name: cimreg
    app.kubernetes.io/part-of: container-image-registry
    app.kubernetes.io/managed-by: kubectl

    # operational classification
    workload-type: stateful
    exposure: internal

  annotations:
    description: "Container Image Registry (cimreg)"
    owner: "mx"




# namespaced resources
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cimreg-sc
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer # PV is created only when the pod using a PVC (taht uses that SC) is scheduled, not before
reclaimPolicy: Retain # When PVC is deleted, PV is not deleted; data persists on the node - see https://kubernetes.io/docs/concepts/storage/storage-classes/
parameters:
  storageType: hostpath # Volumes are hostPath folders 
  path: /var/lib/cimreg-local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cimreg-pvc
  namespace: cimreg
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cimreg-sc
  resources:
    requests:
      storage: 10Gi

