# namespaced resources

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxui-dep-browser
  namespace: mxui
  labels:
    app.kubernetes.io/name: browser-ui
    app.kubernetes.io/component: browser-ui
    app.kubernetes.io/part-of: mxui    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: browser
  template:
    metadata:
      labels:
        app.kubernetes.io/name: browser
    spec:
      containers:
        - name: cfirefox
          image: jlesage/firefox:latest
          ports:
            - containerPort: 5800
              name: port-ct-svc
          # Resources are "strictly necessary" for browsers to prevent node OOM
          resources:
            limits:
              cpu: "750m"
              memory: "768Mi"
            requests:
              memory: "512Mi"
              cpu: "500m"
          # Fix for Firefox: Shared Memory mount
          volumeMounts:
            - name: cache-shm
              mountPath: /dev/shm    
          # probe begin    
          livenessProbe:
            tcpSocket:
              port: port-ct-svc
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: port-ct-svc
            initialDelaySeconds: 5
          # probe end
      # Fix for Firefox: Shared Memory mount
      volumes:
        - name: cache-shm
          emptyDir:
            medium: Memory
