apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cimreg-pvc
  namespace: cimreg
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
