# clustered resources

{{- if or .Values.enabled.all .Values.enabled.mnf.sc }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cimreg-sc
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: cimreg
    app.kubernetes.io/component: storage
  annotations:
    owner: "abtransitionit"
    description: "defines/configures the external storage manager to provision storage for app cimreg"
provisioner: openebs.io/local
reclaimPolicy: Retain # When PVC is deleted, PV is not deleted; data persists on the node - see https://kubernetes.io/docs/concepts/storage/storage-classes/
volumeBindingMode: WaitForFirstConsumer # PV is created only when the pod using a PVC (taht uses that SC) is scheduled, not before
allowVolumeExpansion: true
parameters:
  storageType: hostpath # Volumes are hostPath folders 
  basePath: {{ .Values.cimreg.hostPath | quote }} # base path on the node where hostPath folders are created for each PV
{{- end }}


# This covers the "Legacy/CAS" logic seen in the default class
# cas.openebs.io/config: |
#   - name: StorageType
#     value: "hostpath"
#   - name: BasePath
#     value: "/var/lib/cimreg-local"
