# namespaced resources

{{- if or .Values.enabled.all .Values.enabled.mnf.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cimreg-pvc
  # namespace is injected by helm
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: cimreg
    app.kubernetes.io/component: storage
  annotations:
    owner: "abtransitionit"
    description: "requests storage:location/volume:path/folder:path when needed"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cimreg-sc
{{- end }}
